# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74b883b420b23d489706218b25c5c69ff6e27206687d6ee08ca06b54ebea216975c3521d00631cd041415ad02234163e1344bd8cf58fcfcdd859e280632f2d90

test:
  secret_key_base: de2553cf8c0fca2f16a2e0f1c51972957c27817ee6c95ad16e7eb6135512454e5dc3a91baa46ed1066cb2e4a8656a8d253381bcc34c703e00da93f1e95525285

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
